### ISSUE TITLE
locals for GUI is set to spanish

### ISSUE THREAD

**Issue by SwissFred57** [MANOLOV02/BG3-UTAM#2]
can you change the locals used on the GUI to be english like press 'OK' but now 'Aceptar'

**Comment by MANOLOV02** [comment]
I will look into it. It’s entirely handled by my visual studio automated dialogs and  didn’t noticed that some of those buttons are I Spanish. (I am Spanish native speaking). Will “Fix” it if I can on next release

**Comment by MANOLOV02** [comment]
Fixed the ones I found. let me know if yo still have spanish in some part specifically where and will fix it.

**Comment by SwissFred57** [comment]
where do i download the latest version 5.45 ?

**Comment by SwissFred57** [comment]
looks ok now thanks

**Comment by MANOLOV02** [comment]
Great!
