### ISSUE TITLE
default add to game should be unchecked

### ISSUE THREAD

**Issue by SwissFred57** [MANOLOV02/BG3-UTAM#3]
should be unchecked on default if not yout get the game with a lot of mods on testing
![image](https://github.com/MANOLOV02/BG3-UTAM/assets/123299068/2df14f69-5efe-47cf-a438-515ab8d1e57b)

**Comment by MANOLOV02** [comment]
Hi thanks for your comments. This is not really an issue is rather user preferences. I do prefer to have it checked, if you uncheck it it will remaint that way.
