### ISSUE TITLE
Duplicating treasure tables

### ISSUE THREAD

**Issue by ardenova** [MANOLOV02/BG3-UTAM#7]
When changing the name of treasure tables in the editor it will duplicate them in treasuretables.txt and have to be removed manually.  

Also, this causes the treasure tables to sometimes be unable to be removed from the world injection in object editors.  For instance, if I delete an entry from the world injection and save it will just revert back.

**Comment by MANOLOV02** [comment]
You are right. Released a 5.6 fixed version
