### ISSUE TITLE
get Virus message on downloading 5.7

### ISSUE THREAD

**Issue by SwissFred57** [MANOLOV02/BG3-UTAM#9]
i got a message that there is a Virus on downloading version 5.7

**Comment by MANOLOV02** [comment]
IT IS AN EXECUTABLE FILE AND THEREFORE WIL BE FLAGGED AS RISKY FOR MOST ANTIVIRUS. FEEL FREE TO DOWNLOAD THE SOURCE CODE AND RECOMPILE IT AFTER ANALIZING THERE IS NO MALICIOUS CODE INSIDE
